vim.o.number = true                  -- Numero de lineas a la izq
vim.o.relativenumber = true          -- Numero relativo al cursor a la izq
vim.o.wrap = false                   -- Hacer que una linea que sobresale de la pantalla ocupe mas de una linea
vim.o.tabstop = 4                    -- 2 espacios al presionar tab
vim.o.shiftwidth = 4                 -- 2 espacios como largo de identación
vim.o.expandtab = true               -- Expandir tabs como espacios
vim.o.autoindent = true              -- Copiar identación de la linea actual al crear una nueva
vim.o.cursorline = true              -- Resaltado de la fila en la que se encuentra el cursor actualmente
vim.o.termguicolors = true           -- Habilita colores RGB (24bit)
vim.o.signcolumn = "yes"             -- Columna lateral siempre visible (Espacio para iconos, alertas, etc)
vim.o.swapfile = false               -- Eliminar el archivo de recuperacion ante fallos
vim.o.clipboard = "unnamedplus"      -- Sincronizar el portapapeles de neovim con el del sistema
vim.o.splitright = true              -- :vsplit abre a la derecha
vim.o.splitbelow = true              -- :split abre abajo
vim.o.ignorecase = true              -- Ignorar mayusculas o minusculas al buscar
vim.o.smartcase = true               -- Si intercalamos mayusculas y minusculas entonces se asume el case-sensisitve
vim.o.backspace = "indent,eol,start" -- Comportamiento de backspace moderno
